services:

  db:
    image: postgres:16.0-alpine
    container_name: db
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./.env
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - ./.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin/data
    ports:
      - 8080:80
    depends_on:
      - db
  backend:
    image: elenashirokova/film_backend:latest
    container_name: backend
    restart: always
    expose:
      - 3000
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    image: elenashirokova/film_frontend:latest
    container_name: frontend
    volumes:
      - ./frontend/:/app/result_dist
    depends_on:
      - db
  nginx:
    image: nginx:1.21.3
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot/
      - ./certbot/conf/:/etc/nginx/ssl/
      - ./frontend/dist:/usr/share/nginx/html/
    restart: always
    depends_on:
      - backend
      - frontend
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/

volumes:
  db:
  result_dist:
  pgadmin-data:
