version: '3.3'
services:

  db:
    image: postgres:16.0-alpine
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./.env
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin/data
    ports:
      - 8080:80
    depends_on:
      - postgres
  backend:
    image: elenashirokova/film_backend:latest
    restart: always
    expose:
      - 3000
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    image: elenashirokova/film_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
  nginx:
    image: nginx:1.21.3
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot/
      - ./certbot/conf/:/etc/nginx/ssl/
      - ../frontend/build:/usr/share/nginx/html/
    restart: always
    depends_on:
      - backend
      - frontend
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/

volumes:
  db:
  result_build:
  pgadmin-data: